# TODO: Add your project title here
title: Flutter Docker Template
description: {{site.data.github.project.description}}
baseurl: ""
url: {{site.data.github.project.repository_url}}
github: [metadata]
exclude: 
  - "Dockerfile"
  - "jekyll-doc-web.sh"
  - "Gemfile"
  - "Gemfile.lock"
  - ".dockerignore"
  - ".gitignore"
  - ".editorconfig"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
color_scheme: tarek

# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  tutorials:
    permalink: "/:collection/:path/"
    output: false

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    # tutorials:
      # Give the collection a name
      # name: Tutorial
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true

nav_external_links:
  - title: Source Code
    url: {{site.data.github.project.repository_url}}
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

# Aux links for the upper right navigation
aux_links:
  "View On Github":
    - {{site.data.github.project.repository_url}}

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

footer_content:
  -  Found an error? Feel free to file a <a href="{{site.data.github.project.repository_url}}/issues">GitHub Issue</a>. :)

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: {{site.data.github.project.repository_url}} # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
